export const PROJECTS = [
  {
    id: "muelitas-challenge",
    type: "web",
    name: "Muelitas Challenge Ranking 2024",
    url: "https://soloqchallenge.pages.dev",
    desc_es: "Sitio web para el evento Muelitas Challenge 2024 que muestra una tabla de clasificación de streamers de Twitch ordenado por su rango de League of Legends.<br><br>El evento tuvo una duración de 1 mes (1 de marzo 2024 - 31 de marzo 2024) y el sitio web obtuvo un tráfico de alrededor de 1,75 millones de solicitudes y 30 mil visitantes únicos en total.",
    desc_en: "Website for the Muelitas Challenge event that displays a leaderboard of Twitch streamers sorted by their League of Legends rank.<br><br>The event lasted for 1 month (March 1, 2024 - March 31, 2024), and the website had a traffic of around 1.75 million requests and 30k unique visitors in total.",
    images: ["muelitaschallenge-website.jpg"],
    start_month: 2,
    start_year: 2024,
    end_month: 4,
    end_year: 2024,
    desc_li_es: [
      "Desarrolló una tabla de clasificación para el juego League of Legends agregando una lista de streamers con sus respectivas cuentas de juego y redes sociales. Usando Nuxt alojado en Cloudflare Pages.",
      "Diseñó una base de datos que guarda información sobre Twitch y League of Legends de cada streamer para ser mostradas directamente de manera visual en el sitio web.",
      "Implementó algunos cron triggers que actualizan periódicamente la información correspondiente a cada streamer para mantener actualizado el sitio web. Usando Cloudflare Workers junto con las API de Riot Games y Twitch."
    ],
    desc_li_en: [
      "Developed a leaderboard for the game League of Legends by adding a list of streamers with their respective game accounts and social media. Using Nuxt hosted on Cloudflare Pages.",
      "Designed a database that stores information about Twitch and League of Legends for each streamer to be displayed visually on the website.",
      "Implemented some cron triggers that periodically update the information corresponding to each streamer to keep the website up-to-date. Using Cloudflare Workers in conjunction with the Riot Games and Twitch APIs."
    ],
    tags: ["Nuxt", "Vue.js", "JavaScript", "Node.js", "TypeScript", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages", "Cloudflare Workers", "Cloudflare D1", "Cron Triggers", "Riot Games API", "Twitch API"],
    repository: "https://github.com/ahmedrangel/muelitaschallenge"
  },
  {
    id: "animed",
    type: "web",
    name: "Animed | TV Anime Web Library",
    url: "https://animed.ahmedrangel.com",
    desc_es: "Cliente web para buscar información relacionada con series de TV anime.",
    desc_en: "Web client to search for TV anime series related information.",
    images: ["anime-website.jpg", "anime-website-2.jpg", "anime-website-3.jpg", "anime-website-4.jpg"],
    start_month: 2,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["Nuxt", "Vue.js", "JavaScript", "TypeScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages", "GraphQL", "AniList API"],
    repository: "https://github.com/ahmedrangel/animed"
  },
  {
    id: "unbotme",
    type: "web",
    name: "Unbot.me",
    url: "https://unbot.me",
    desc_es: "Unbotme es un bot para Twitch diseñado para banear automáticamente a bots identificados que suelen acechar persistentemente en múltiples canales.",
    desc_en: "Unbotme is a bot for Twitch designed to automatically ban identified bots that persistently lurk in channels.",
    images: ["unbotme-website.jpg"],
    start_month: 1,
    start_year: 2024,
    end_month: 11,
    end_year: 2024,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["Nuxt", "Vue.js", "JavaScript", "TypeScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages", "WebSocket", "Twitch API"],
    repository: "https://github.com/ahmedrangel/unbot.me"
  },
  {
    id: "drawmond",
    type: "web",
    name: "Drawmond",
    url: "https://drawmond.ahmedrangel.com",
    desc_es: "Juego web enfocado a creadores de contenido de Twitch, donde desafían a su audiencia a adivinar los dibujos que el streamer crea.",
    desc_en: "Web game focused on Twitch content creators, where they challenge their audience to guess the drawings that the streamer creates.",
    images: ["drawmond-website.jpg"],
    start_month: 8,
    start_year: 2023,
    end_month: 8,
    end_year: 2023,
    desc_li_es: [
      "Desarrolló un juego web enfocado a creadores de contenido de Twitch, donde éstos desafían a su audiencia a descifrar los dibujos que este crea. Usando Nuxt alojado en Cloudflare Pages.",
      "Implementó un lienzo con todas las herramientas básicas para el proceso de dibujo.",
      "Empleó un WebSocket de Twitch para capturar y procesar los mensajes provenientes de la audiencia y gestionó todos los eventos que tienen lugar durante el juego, incluyendo inicio, aciertos, puntuaciones, transiciones, temporizador."
    ],
    desc_li_en: [
      "Developed a web game focused on Twitch content creators, where they challenge their audience to guess the drawings that the streamer creates. Using Nuxt hosted on Cloudflare Pages.",
      "Implemented a canvas with all the basic tools for the drawing process.",
      "Used a Twitch WebSocket to capture and process the messages coming from the audience and managed all the events that take place during the game, including start, hits, evaluation, transitions, timer."
    ],
    tags: ["Nuxt", "Vue.js", "JavaScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages", "WebSocket"],
    repository: "https://github.com/ahmedrangel/drawmond"
  },
  {
    id: "kickclips",
    type: "web",
    name: "Kick Clips",
    url: "https://kickclips.ahmedrangel.com",
    desc_es: "Herramienta en línea gratuita para descargar clips MP4 de kick.com.",
    desc_en: "Free online tool for downloading MP4 clips from kick.com.",
    images: ["kickclips-website.jpg"],
    start_month: 6,
    start_year: 2023,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["Nuxt", "Vue.js", "JavaScript", "TypeScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages"],
    repository: "https://github.com/ahmedrangel/kickclips"
  },
  {
    id: "instagram-scraper",
    type: "node",
    name: "Instagram Media Scraper",
    desc_es: "Este es un repositorio con varios métodos para obtener información pública y medios (imágenes, videos, carrusel) de cualquier publicación o reel de Instagram sin API. Podrás obtener información, versiones de imágenes, versiones de video y medios carrusel con sus respectivas versiones de imagen y/o versiones de video de cada uno de ellos.",
    desc_en: "This is repository with various methods to get public information and media (images, videos, carousel) from every instagram post or reel URL without API. You can get information, image versions, video versions and carousel media with their respective image versions and/or video versions of each of them.",
    start_month: 6,
    start_year: 2023,
    end_month: 1,
    end_year: 2024,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["JavaScript", "ES6+", "Node.js", "Web Scraping"],
    repository: "https://github.com/ahmedrangel/instagram-media-scraper"
  },
  {
    id: "saldometrobus",
    name: "Saldo Metrobus",
    url: "https://saldometrobus.yizack.com",
    desc_es: "Panamá Metrobus Saldo es una app para consultas de saldo y movimientos de todas las tarjetas Metro y Metrobus de la Ciudad de Panamá.",
    desc_en: "Panama Metrobus Balance is an app for balance and movements inquires for all Metro and Metrobus cards in Panama City.",
    images: ["saldometrobus-website.jpg"],
    start_month: 1,
    start_year: 2022,
    end_month: 6,
    end_year: 2022,
    desc_li_es: ["Colaboró junto a <a href=\"https://yizack.com\" target=\"_blank\">Yizack Rangel</a> en el desarrollo de un proyecto web y de Android de 25000+ descargas totales, actualmente ayuda a 6500+ usuarios a conocer el saldo y movimientos las tarjetas de Metro y Metrobús."],
    desc_li_en: ["Collaborated with <a href=\"https://yizack.com\" target=\"_blank\">Yizack Rangel</a> in the development of a web and Android project with 25,000+ downloads totals, currently helps 6500+ users to know the balance and movements of the Metro and Metrobús cards."],
    tags: ["Android Studio", "Java", "PHP", "PostgreSQL", "AWS Elastic Beanstalk", "Bootstrap 5"]
  },
  {
    id: "pespgg",
    type: "web",
    name: "PESP.GG Website",
    url: "https://pesp.gg",
    desc_es: "El sitio web PESP.GG es un proyecto colaborativo entre programadores, diseñadores gráficos y la empresa Panama Esports Productions para la creación del sitio web oficial de la empresa.",
    desc_en: "The PESP.GG website is a collaborative project between programmers, graphic designers and the company Panama Esports Productions for the creation of the company's official website.",
    images: ["pespgg-website.jpg"],
    start_month: 9,
    start_year: 2021,
    end_month: 13,
    end_year: null,
    desc_li_es: [
      "El proyecto se desarrolló inicialmente utilizando PHP alojado en AWS EC2 y luego migró a Nuxt alojado en Cloudflare Pages.",
      "Desarrolló un proyecto de sitio web de deportes electrónicos utilizando Nuxt alojado en Cloudflare Pages.",
      "Implementó un panel para administrar las publicaciones del sitio web y ver estadísticas.",
      "Diseñó una Base de Datos para las publicaciones del sitio web usando SQLite en desarrollo y Cloudflare D1 en producción usando Drizzle-ORM para consultas SQL.",
      "Implementó un sistema de almacenamiento de contenido html de imágenes y publicaciones usando Cloudflare R2."
    ],
    desc_li_en: [
      "The project was initially developed using PHP hosted on AWS EC2, then migrated to Nuxt hosted on Cloudflare Pages.",
      "Developed an Esports website project using Nuxt hosted on Cloudflare Pages.",
      "Implemented an admin dashboard to manage the website's posts and see statistics.",
      "Designed a Database for the website's posts using SQLite in development and Cloudflare D1 in production using Drizzle-ORM for SQL queries.",
      "Implemented an images and posts html content storage system using Cloudflare R2."
    ],
    tags: ["Cloudflare D1", "Cloudflare R2", "Nuxt", "Vue.js", "JavaScript", "TypeScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages"],
    repository: "https://github.com/yizack/pesp.gg"
  },
  {
    id: "bayza",
    type: "web",
    name: "Bayza Website",
    url: "https://bayza.music",
    desc_es: "Sitio Web de Artista Musical",
    desc_en: "Music Artist Website",
    images: ["bayza-website.jpg"],
    start_month: 1,
    start_year: 2020,
    end_month: 13,
    end_year: null,
    desc_li_es: [
      "Diseñó un sitio web enfocado a exhibir la colección completa de canciones del artista,su biografía, videos, detalles e hipervínculos relevantes.",
      "Desarrolló el sitio utilizando Nuxt alojado en Cloudflare Pages."
    ],
    desc_li_en: [
      "Designed a website focused on showcasing the artist's full collection of songs, biography, videos, details and relevant hyperlinks.",
      "Developed using Nuxt hosted on Cloudflare Pages."
    ],
    tags: ["Nuxt", "Vue.js", "JavaScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages"],
    repository: "https://github.com/ahmedrangel/bayza"
  },
  {
    id: "expedition",
    type: "web",
    name: "Expedition (Landing Page) | Event by TRIEX",
    url: "https://expedition.pesp.gg",
    desc_es: "Landing Page para el evento Expedition por TRIEX. Organizado por PESP",
    desc_en: "Landing Page for Expedition event by TRIEX. Organized by PESP",
    images: ["expedition-website-1.jpg", "expedition-website-2.jpg", "expedition-website-3.jpg", "expedition-website-4.jpg"],
    start_month: 7,
    start_year: 2024,
    end_month: 7,
    end_year: 2024,
    desc_li_es: [
      "Diseñó un landing page e implementó dos registros, uno de inscripciones para participar en el evento y otro para participar un sorteo.",
      "Desarrolló el landing page utilizando Nuxt alojado en Cloudflare Pages.",
      "Implementó el sistema de registros utilizando Cloudflare D1."
    ],
    desc_li_en: [
      "Designed a landing page and implemented two registrations, one for participating in the event and one for the giveaway.",
      "Developed the landing page using Nuxt hosted on Cloudflare Pages.",
      "Implemented the registration system using Cloudflare D1."
    ],
    tags: ["Nuxt", "Vue.js", "JavaScript", "TypeScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages", "Cloudflare D1"]
  },
  {
    id: "streamers-queue",
    type: "web",
    name: "Streamers Queue",
    url: "https://streamersqueue.ahmedrangel.com",
    desc_es: "Sitio web que recopila datos de partidas clasificatorias de League of Legends utilizando cuentas de streamers para mostrar distintas estadísticas y tablas de calsificación.",
    desc_en: "Website that collects data from League of Legends ranked matches using streamer accounts to display different statistics and ranking tables.",
    images: ["streamersqueue-website.jpg", "streamersqueue-website-2.jpg", "streamersqueue-website-3.jpg"],
    start_month: 4,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: [
      "Desarrolló distintas tablas de estadísticas y de clasificación tomando en cuenta la región de pertenencia agregando una lista de streamers con sus respectivas cuentas de juego y redes sociales. Usando Nuxt alojado en Cloudflare Pages.",
      "Diseñó una base de datos que guarda información sobre Twitch y League of Legends de cada streamer para ser mostradas directamente de manera visual en el sitio web.",
      "Implementó algunos cron triggers que actualizan periódicamente la información correspondiente a cada streamer para mantener actualizado el sitio web. Usando Cloudflare Workers junto con las API de Riot Games y Twitch."
    ],
    desc_li_en: [
      "Developed different statistics and ranking tables taking into account the region of belonging, adding a list of streamers with their respective game accounts and social media. Using Nuxt hosted on Cloudflare Pages.",
      "Designed a database that stores information about Twitch and League of Legends of each streamer account to be displayed directly on the website.",
      "Implemented some cron triggers that update periodically the information corresponding to each streamer and region to keep the website updated. Using Cloudflare Workers along with Riot Games API and Twitch API."
    ],
    tags: ["Nuxt", "Vue.js", "JavaScript", "TypeScript", "Node.js", "HTML", "CSS", "Bootstrap 5", "Cloudflare Pages", "Cloudflare Workers", "Cloudflare D1", "Cron Triggers", "Riot Games API", "Twitch API"],
    repository: "https://github.com/ahmedrangel/streamersqueue"
  },
  {
    id: "snapsasve-media-downloader",
    type: "npm",
    name: "snapsasve-media-downloader",
    url: "https://www.npmjs.com/package/snapsave-media-downloader",
    desc_es: "Descarga media de Instagram, Facebook y TikTok utilizando snapsave.app",
    desc_en: "Download Instagram, Facebook and TikTok media using snapsave.app downloader",
    start_month: 4,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["TypeScript", "Node.js", "NPM"],
    repository: "https://github.com/ahmedrangel/snapsave-media-downloader"
  },
  {
    id: "gql-payload",
    type: "npm",
    name: "gql-payload",
    url: "https://www.npmjs.com/package/gql-payload",
    desc_es: "Este es un fork optimizado de <a href='https://github.com/atulmy/gql-query-builder' target='_blank'>gql-query-builder</a> con características adicionales para generar payloads GraphQL utilizando objetos JavaScript simples (JSON).",
    desc_en: "This is an optimized fork of <a href='https://github.com/atulmy/gql-query-builder' target='_blank'>gql-query-builder</a> with extra features for generating GraphQL payloads using plain JavaScript Objects (JSON).",
    start_month: 8,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["TypeScript", "Node.js", "NPM", "GraphQL"],
    repository: "https://github.com/ahmedrangel/gql-payload"
  },
  {
    id: "tetrio-bot",
    type: "node",
    name: "tetrio-bot",
    desc_es: "Un bot de Tetris capaz de jugar automáticamente partidas multijugador personalizadas en TETR.IO. Utiliza una versión modificada de ElTetris para analizar el tablero actual y realizar movimientos óptimos, y la biblioteca @haelp/teto para interactuar con la API del juego principal.",
    desc_en: "A Tetris bot capable of automatically playing custom multiplayer matches in TETR.IO. It uses a modified version of ElTetris to analyze the current board for optimal moves and the @haelp/teto library to interact with main game API.",
    start_month: 9,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["TypeScript", "Node.js", "TETR.IO"],
    repository: "https://github.com/ahmedrangel/tetrio-bot"
  },
  {
    id: "nuxt-ripple",
    type: "npm",
    name: "nuxt-ripple",
    url: "https://nuxt-ripple.pages.dev",
    desc_es: "Añade efectos de animación de ondas simples a tus elementos.",
    desc_en: "Add simple ripple animation effects to your elements.",
    start_month: 11,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["Nuxt", "Vue.js", "TypeScript", "Node.js"],
    repository: "https://github.com/ahmedrangel/nuxt-ripple"
  },
  {
    id: "vuetracker",
    type: "web",
    name: "VueTracker",
    url: "https://vuetracker.nuxt.dev",
    images: ["vuetracker-website.jpg", "vuetracker-website-2.jpg", "vuetracker-website-3.jpg"],
    desc_es: "Descubre los plugins y tecnologías que potencian aplicaciones web hechas con Vue",
    desc_en: "Discover the plugins and technologies powering websites made with Vue.",
    start_month: 12,
    start_year: 2024,
    end_month: 13,
    end_year: null,
    desc_li_es: null,
    desc_li_en: null,
    tags: ["Nuxt", "Vue.js", "TypeScript", "HTML", "CSS", "TailwindCSS", "Cloudflare Pages", "Cloudflare D1"],
    repository: "https://github.com/ahmedrangel/vuetracker"
  }
];
