export default {
  lang: "en",
  name: "Eliezer Ahmed Rangel Baysa",
  name_abreviated: "Eliezer A. Rangel B.",
  about_me: "About Me",
  bio: "Actualmente, me destaco como un desarrollador entusiasta que ha acumulado experiencia a lo largo de los años en varios tipos de tecnologías y frameworks, tanto en el ámbito frontend como en el backend, para la creación de aplicaciones web altamente eficientes y funcionales. Mi pasión desde pequeño por el mundo de las computadoras y las tecnologías emergentes impulsa constantemente mi crecimiento personal y profesional. Cuento con habilidades significativas en el desarrollo de aplicaciones web, automatización de sistemas, administración de bases de datos y la implementación de interfaces de programación de aplicaciones.",
  degree: "Computer and Systems Engineering",
  bachelor: "High School Diploma, Science",
  years_old: "years old",
  address: "Panama City, Panama",
  education: "Education",
  utp: "Technological University of Panama",
  pps: "Pedro Pablo Sanchez High School",
  at: "at",
  panama: "Panama",
  panama_city: "Panama City",
  la_chorrera: "La Chorrera",
  months: [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
  ],
  languages: "Languages",
  spanish: "Spanish",
  english: "English",
  native: "Native",
  intermediate: "Intermediate",
  advanced: "Advanced",
};