export default {
  lang: "en",
  name: "Eliezer Ahmed Rangel Baysa",
  name_abreviated: "Eliezer A. Rangel B.",
  about_me: "About Me",
  about: "About",
  bio: "Currently, I stand out as an enthusiastic developer who has gathered experience over the years in various types of technologies and frameworks, both on the frontend and backend sides, for creating highly efficient and functional web applications. My lifelong passion for the world of computing and emerging technologies continually drives my personal and professional growth. I possess substantial skills in web application development, system automation, database management, and the implementation of application programming interfaces.",
  degree: "Computer and Systems Engineering",
  bachelor: "High School Diploma, Science",
  years_old: "years old",
  address: "Panama City, Panama",
  education: "Education",
  utp: "Technological University of Panama",
  pps: "Pedro Pablo Sanchez High School",
  at: "at",
  panama: "Panama",
  panama_city: "Panama City",
  la_chorrera: "La Chorrera",
  months: [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
  ],
  languages: "Languages",
  spanish: "Spanish",
  english: "English",
  native: "Native",
  intermediate: "Intermediate",
  advanced: "Advanced",
};