export default {
  lang: "es",
  name: "Eliézer Ahmed Rangel Baysa",
  name_abreviated: "Eliézer A. Rangel B.",
  about_me: "Sobre Mí",
  about: "Sobre Mí",
  bio: "Actualmente, me destaco como un desarrollador entusiasta que ha acumulado experiencia a lo largo de los años en varios tipos de tecnologías y frameworks, tanto en el ámbito frontend como en el backend, para la creación de aplicaciones web altamente eficientes y funcionales. Mi pasión desde pequeño por el mundo de las computadoras y las tecnologías emergentes impulsa constantemente mi crecimiento personal y profesional. Cuento con habilidades significativas en el desarrollo de aplicaciones web, automatización de sistemas, administración de bases de datos y la implementación de interfaces de programación de aplicaciones.",
  degree: "Lic. Ingeniería en Sistemas y Computación",
  bachelor: "Bachiller en Ciencias",
  years_old: "años",
  address: "Ciudad de Panamá, Panamá",
  address2: "La Chorrera, Panamá",
  education: "Eduación",
  utp: "Universidad Tecnolónica de Panamá",
  pps: "Escuela Secundaria Pedro Pablo Sánchez",
  at: "en",
  panama: "Panamá",
  panama_city: "Ciudad de Panamá",
  la_chorrera: "La Chorrera",
  months: [
    "Enero", "Febrero", "Marzo", "Abril",
    "Mayo", "Junio", "Julio", "Agosto",
    "Septiembre", "Octubre", "Noviembre", "Diciembre", "Presente"
  ],
  languages: "Idiomas",
  spanish: "Español",
  english: "Inglés",
  native: "Nativo",
  intermediate: "Intermedio",
  advanced: "Avanzado",
  main_skills: "Habilidades principales",
  web_development: "Desarrollo Web",
  javascript: "JavaScript",
  databases: "Bases de Datos",
  serverless: "Serverless",
  software_and_tools: "Software y Herramientas",
  operating_systems: "Sistemas Operativos",
  projects: "Proyectos",
  repository: "Repositorio",
  download_resume: "Descargar CV",
};