export default {
  lang: "en",
  name: "Eliezer Ahmed Rangel Baysa",
  name_abreviated: "Eliezer A. Rangel B.",
  about_me: "About Me",
  about: "About",
  bio: "I stand out as an enthusiastic developer who constantly strives to improve their skills and aims to apply best practices in every project. With years of experience across various technologies and frameworks, both in frontend and backend, for creating highly efficient and functional web applications. My lifelong passion for the world of computing and emerging technologies continually drives my personal and professional growth. I possess strong skills in web application development, system automation, database management, and API development and integration.",
  degree: "Computer and Systems Engineering",
  bachelor: "High School Diploma, Science",
  years_old: "years old",
  address: "Panama City, Panama",
  address2: "La Chorrera, Panama",
  education: "Education",
  utp: "Technological University of Panama",
  pps: "Pedro Pablo Sanchez High School",
  at: "at",
  panama: "Panama",
  panama_city: "Panama City",
  la_chorrera: "La Chorrera",
  months: [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December", "Present"
  ],
  languages: "Languages",
  spanish: "Spanish",
  english: "English",
  native: "Native",
  intermediate: "Intermediate",
  advanced: "Advanced",
  skills: "Skills",
  main_skills: "Main Skills",
  web_design: "Web Design",
  javascript: "JavaScript",
  serverless: "Serverless",
  databases: "Databases",
  software_and_tools: "Software & Tools",
  operating_systems: "Operating Systems",
  projects: "Projects",
  repository: "Repository",
  download_resume: "Download Resume",
  tools: "Tools",
  cloud: "Cloud",
  apis: "APIs",
  server_administration: "Server Administration",
  view: "View",
  open_source_contributions: "Open Source Contributions",
  contributions: "Contributions"
};
